export const APIConstant = {

    // Visitor API
    SIGN_UP: `/users/register`,
    VERIFY_SIGNUP_OTP: '/users/verifyotp',
    LOGIN: '/auth/local',
    GET_USER: '/users/all-user',
    FORGET_PASSWORD: '/users/forgotPassword',
    CHANGE_PASSWORD: '/users/ResetPassword',
    VISITOR_INFORMATION_FORM: '/visitor/add',
    ADDD_VISITOR_IMAGE_UPLOAD: '/visitor/avatar',
    VISITOR_ADDRESS: '/visitor/address',
    OBJECTIVE_INFORMATION: '/visitor/objective',
    POLITICAL_INFORMATION: '/visitor/political',
    VISITOR_LIST: '/visitor/visitor-list',
    SEARCH_VISITOR_LIST: '/visitor/search-visitor-list',
    VISITOR_DETAIL: '/visitor/get',
    PROXIMITY_OPTION_DATA: '/visitor/proximity',
    WHOM_TO_MEET: '/visitor/whomToMeet',
    VISITOR_CATEGORY: '/visitor/visitorCategory',
    VISITOR_PURPOSE: '/visitor/visitPurpose',
    VISITOR_IMAGE_GET: '/visitor/get-avatar',
    VISITOR_POLITICAL_INCLINATION: '/visitor/politicalInclination',
    VISITOR_LOCATION_OF_MEETING: '/visitor/meetingLocation',
    VISITOR_LIST_FILTER: '/visitor/visitor-list?',
    VISITOR_ANALYTIC_DATA: '/visitor/visit-analytics',
    DATA_BY_UNIQUE_VISITOR_ID: '/visitor/visits',
    EXIST_VISITOR_FORM: '/visitor/re-visits',
    Total_Visit_List:'/visitor/visits',
    Visitor_Revisit:'/visitor/re-visits',
    GET_CASTES: '/visitor/getCaste',
    BOOTH_NAME_BY_NUMBER: '/visitor/json-files',
    VISITOR_ANALYTIC_GRAPH_DATA: '/visitor/graph',
    VISITOR_OCCUPTION:'/visitor/occupation',

    // Schedular API 
    GET_DROP_DOWN_META_DATA: '/admin/dropdown',
    SCHEDULE_MEET_FORM_SUBMIT: '/admin/event',
    UPLOAD_DOC_IN_SCHEDULE: '/admin/document',
    GET_EVENT_LIST: '/admin/event-list',
    EVENT_DETAIL: '/admin/get-event',
    SCHEDULAR_ANALYTIC_DATA: '/admin/analytics',
    GET_CALENDER_EVENT: '/admin/calendar',
    SCHEDULE_ANALYTIC_GRAPH_DATA:'/admin/events-scheduling/graph',
    CLOSE_CALENDAR_EVENT: '/admin/close-event',
    WORKER_INFORMATION_FORM: '/worker/add',
    WORKER_ADDRESS:"/worker/workerAddress",
    GET_WORKER_DATA:'/worker/getWorker',
    WORKER_OBJECTIVE_INFORMATION: '/worker/workerObjectiveInfo',
    ADD_WORKER_IMAGE_UPLOAD:"/worker/avatar",
    WORKER_LIST: '/worker/workerList',
    WORKER_BOOTH_NAME_BY_NUMBER :'/worker/json-files',
    WORKER_IMAGE_GET: '/worker/getAvatar',
    GET_OTHER_PARTY_WORKER_LIST: '/worker/getOtherPartyWorkerList',
    GET_OTHER_PARTY_WORKER: '/worker/getOtherPartyWorker',
    ADD_OTHER_PARTY_WORKER: '/worker/addOtherPartyWorker',
    GET_VOTER_LIST_DETAIL: '/visitor/voters',
    SCHEDULE_MEET_WITH_CALENDAR_ACCESS_FORM_SUBMIT: '/admin/set-oauth-credentials',
    GET_TYPE_OF_WORKER_OPTION_DATA: '/worker/getWorkerCategory',
    GET_TYPE_OF_TRAINING_OPTION_DATA: '/worker/skills',
    OTHER_WORKER_PARTY_AFFILIATION:'/worker/getPartyAffiliation',
    WORKER_CREATE_TASK_FORM: '/worker/addTask',
    GET_TYPE_OF_TASK_OPTION_DATA: '/worker/typeOfTask',
    GET_WORKER_TASK_BYID:'/worker/getTaskByWorkerId',
    GET_WORKER_MANAGEMENT_GRAPH_DATA:'/worker/workerGraph',
    GET_CALENDER_TASK: '/worker/taskList',
    CLOSE_WORKER_TASK: '/worker/closeTask',
    WORKER_ANALYTIC_DATA: '/worker/workerAnalytics',
    WORKER_AUTO_FILL_DATA:'/worker/getWorkersData',
     KMS_GRAPH_DATA:'/kms/graph',
    SCHEDULE_ADMIN_EVENTDATA:'/admin/eventData',
    // KMS API 
    KMS_ANALYTIC_DATA: '/kms/analytics',
    ADD_KMS_DATA_FORM: '/kms/add',
    KMS_LIST :'/kms/list',
    UPLOAD_DOC_IN_KMS: '/admin/document',
    KMS_SEARCH: '/kms/search',
    GET_KMS_BY_ID:'/kms/getKms',
    DELETE_MEDIA_FILE: '/kms/file/delete',
    GET_KMS_UPLOAD_AND_LEADER_OPTION:'/kms/getAssociateMember',
    GET_UPLOAD_BY_OPTION_VALUE:'/kms/getUploadedBy',
    GET_CONSTITUENCY: '/visitor/getconstitution',
    GET_DISTRICT:'/visitor/getDistrict',
    
    
    //graph api 
    GET_FILTER_GENDER :'/visitor/graph-filter-gender',
    GET_FILTER_CASTE:'/visitor/graph-filter-caste',
    GET_FILTER_OCCUPATION :'/visitor/graph-filter-occupation',
    GET_FILTER_PPI:'/visitor/graph-filter-ppi',
    GET_FILTER_PURPOSE :'/visitor/graph-filter-purpose',
    GET_FILTER_TIMEFRAME:'/visitor/graph-filter-timeframe',
    GET_FILTER_VISITOR_CATEGORY :'/visitor/graph-filter-visitor-category',
    GET_FILTER_VISITOR_MEET:'/visitor/graph-filter-whom-visitor-meet',
    GET_FILTER_MEET_STATUS :'/visitor/graph-filter-meet-status',
    GET_FILTER_AGE_GROUP:'/visitor/graph-filter-age-group',
    GET_FILTER_MEET_LOCATION :'/visitor/graph-filter-meet-location',
    GET_FILTER_IS_SAMAJWADI:'/visitor/graph-filter-is-samajwadi',
    GET_FILTER_AREA:'/visitor/graph-filter-area',
    GET_FILTER_DISTRICT_CONSTITUENCY :'/visitor/graph-filter-district-constituency',
};
